# Generated by Django 3.0.8 on 2020-07-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Hall',
            new_name='hall',
        ),
    ]
